import { GameQuestion } from './types/game';

type QuestionSpec = [
  id: string,
  nsfwRating: number,
  text: string,
  options: string[]
];

const buildQuestions = (
  specs: QuestionSpec[],
  categories: string[]
): GameQuestion[] => specs.map(([id, nsfwRating, text, options]) => ({
  id,
  text,
  options,
  score: 1,
  nsfwRating,
  categories
}));

export const howWouldIReactQuestions = buildQuestions([
  ["react-001", 1, "Your plans get cancelled one hour before you were supposed to leave. What's your honest first reaction?", ["Secret relief — pajamas win", "Annoyed because I mentally prepared", "Immediately make better plans", "Pretend it's fine, remember it forever"]],
  ["react-002", 1, "A restaurant brings the wrong order, but it looks surprisingly good. What do you do?", ["Eat it and accept destiny", "Politely ask for the original", "Offer to swap with a friend", "Keep it and still mention the mistake"]],
  ["react-003", 1, "You enter a party where you know only one person, and they disappear. What's your move?", ["Adopt the nearest friendly stranger", "Find the snacks and observe", "Text my missing friend aggressively", "Leave before anyone learns my name"]],
  ["react-004", 1, "A friend posts a terrible photo of you because they look amazing in it. How do you react?", ["Demand an immediate deletion", "Let them have their moment", "Post an even worse photo of them", "Crop myself out and support from afar"]],
  ["react-005", 1, "Someone confidently tells a story about you that is completely wrong. What happens next?", ["Correct every detail publicly", "Let the fictional version become canon", "Interrupt with a better story", "Wait until later and investigate why"]],
  ["react-006", 3, "Your date is 30 minutes late but arrives with a genuinely excellent apology. What do you do?", ["Forgive instantly", "Accept it but stay observant", "Make them earn the recovery", "The attraction has already left the building"]],
  ["react-007", 4, "Your friend asks for honest advice, then does the exact opposite. How do you react?", ["Support them through the consequences", "Deliver one legendary 'I told you so'", "Stop giving free consulting", "Ask for every detail because now it's entertainment"]],
  ["react-008", 4, "An ex reacts to your best-looking story after months of silence. What's your next move?", ["Ignore it with Olympic discipline", "Like the reaction and nothing more", "Send the baitiest possible reply", "Screenshot first, decide with the group chat"]],
  ["react-009", 5, "Your crush admits they used to think you disliked them. How do you respond?", ["Confess I was nervous", "Pretend I was mysterious on purpose", "Ask what changed their mind", "Flirt hard enough to rewrite history"]],
  ["react-010", 5, "A close friend starts dating someone you strongly distrust. What do you do?", ["Say it clearly once", "Investigate before judging", "Stay quiet but remain ready", "Make my face communicate the full report"]],
  ["react-011", 6, "You discover someone you're dating has been asking mutual friends about you. How do you react?", ["Flattered — the research is mutual", "Concerned by the background check", "Ask what they learned", "Feed the friends better material"]],
  ["react-012", 6, "A friend admits they once had a crush on you. What's your instinctive response?", ["Ask when and demand evidence", "Reveal whether it was mutual", "Turn it into a joke immediately", "Re-evaluate the entire friendship timeline"]],
  ["react-013", 7, "Your private message about someone is accidentally shown to that person. What do you do?", ["Own every word", "Explain the missing context", "Leave the country emotionally", "Ask to see what they wrote about me"]],
  ["react-014", 7, "Someone you have intense chemistry with says they aren't ready for anything serious. How do you react?", ["Believe them and step away", "Keep it casual with strict boundaries", "Assume they'll change their mind", "Enjoy the chaos and accept the invoice"]],
  ["react-015", 8, "Your partner is openly flirted with at a party and clearly enjoys the attention. What do you do?", ["Enjoy watching them be desired", "Join the conversation and reclaim the vibe", "Discuss it privately afterward", "Become visibly jealous despite every intention"]],
  ["react-016", 8, "A very spicy message meant for you appears on your partner's screen while friends are nearby. What's your move?", ["Maintain eye contact like nothing happened", "Reply with something even worse", "Hide the phone and save it for later", "Turn red and expose everything"]],
  ["react-017", 9, "A partner calmly suggests exploring non-monogamy together. What's your first reaction?", ["Curious — let's discuss every boundary", "Interested only as a fantasy", "Jealous before the conversation begins", "Certain monogamy is non-negotiable"]],
  ["react-018", 9, "Someone you're intimate with shares a fantasy that genuinely surprises you. How do you respond?", ["Ask questions without judgment", "Admit one of my own", "Need time before answering", "Discover I'm more intrigued than expected"]],
  ["react-019", 10, "You learn that two people in your friend group have been secretly hooking up. What do you do first?", ["Protect the secret", "Demand the complete timeline", "Predict the fallout immediately", "Reveal that I already suspected it"]],
  ["react-020", 10, "Your partner offers to answer one question with complete honesty. What do you ask about?", ["Their strongest unspoken desire", "The person who has tempted them most", "What they wish were different between us", "Whether there's anything they have never told me"]],
  ["react-021", 2, "Everyone starts singing happy birthday to you in a crowded restaurant. How do you react?", ["Perform gratitude like an award winner", "Hide behind the nearest menu", "Conduct the singing like a choir", "Plan revenge on whoever arranged it"]],
  ["react-022", 3, "You accidentally overhear a friend giving you a genuinely beautiful compliment. What do you do?", ["Walk in and make it emotional", "Pretend I heard nothing", "Tease them about it forever", "Return the compliment later without explaining why"]],
  ["react-023", 4, "A friend asks why you muted their stories. How do you answer?", ["Tell the exact truth", "Blame the algorithm", "Unmute them during the conversation", "Ask why they were checking"]],
  ["react-024", 4, "Someone brings an unexpected plus-one to your carefully planned dinner. What's your reaction?", ["Make room and welcome the chaos", "Smile while recalculating everything", "Ask for a warning next time", "Put the surprise guest in charge of dessert"]],
  ["react-025", 5, "Your best friend says the person you're excited about is painfully boring. What do you do?", ["Defend them immediately", "Ask for brutally specific evidence", "Start noticing every dull moment", "Accept that my type needs supervision"]],
  ["react-026", 5, "Your crush asks what your type is while clearly flirting. How do you respond?", ["Describe them without using their name", "Say I don't have a type", "Give an answer designed to make them jealous", "Ask them to guess"]],
  ["react-027", 5, "You accidentally send a dramatic voice note to the person it was about. What's your recovery?", ["Own it before they finish listening", "Delete it and pray", "Send a second note with context", "Turn the drama into a flirt"]],
  ["react-028", 6, "A close friend keeps returning to someone who treats them badly. What do you do this time?", ["Give the honest speech again", "Support them without approving", "Set a boundary around the updates", "Ask what they actually want from me"]],
  ["react-029", 6, "Someone you're dating asks to share locations all the time. What's your response?", ["Agree — convenience, not surveillance", "Decline and explain the boundary", "Share only during plans", "Ask what fear is underneath the request"]],
  ["react-030", 6, "A friend takes credit for an idea you gave them. How do you react?", ["Correct the record calmly", "Confront them privately", "Let it go once and remember", "Present receipts with unnecessary elegance"]],
  ["react-031", 7, "A friend admits they once lied to protect your reputation. What do you do?", ["Thank them and ask no questions", "Demand the complete story", "Worry about what needed protecting", "Admit what I would have done for them"]],
  ["react-032", 7, "A date compares you to their ex and insists it's a compliment. What's your move?", ["Ask exactly how I'm different", "End the comparison immediately", "Make one devastating joke", "File it as evidence and continue"]],
  ["react-033", 7, "Someone you rejected has an unbelievable glow-up and starts dating your friend. How do you react?", ["Genuinely cheer for them", "Question every past decision", "Act cooler than I feel", "Ask my friend for absolutely no details"]],
  ["react-034", 7, "Your friend's crush privately asks whether they're single. What do you do?", ["Play loyal matchmaker", "Send the screenshot immediately", "Ask what their intentions are", "Refuse to become the plot"]],
  ["react-035", 7, "A close friend reads an old message where you once complained about them. What happens next?", ["Explain the moment honestly", "Apologize without defending it", "Ask why they were reading old messages", "Reveal the complaint I wisely never sent"]],
  ["react-036", 8, "Friends keep joking that you and one particular person have obvious chemistry. How do you react?", ["Deny it far too quickly", "Ask the person what they think", "Lean into the joke and test the energy", "Change the subject before my face confesses"]],
  ["react-037", 8, "Your partner repeatedly likes one person's thirst traps. What do you do?", ["Ignore likes as meaningless", "Mention it playfully", "Ask whether there's attraction", "Conduct silent research first"]],
  ["react-038", 8, "Your crush says your outfit is making it difficult to concentrate. What's your response?", ["Act innocent and enjoy the victory", "Return a dangerously specific compliment", "Ask what exactly is distracting", "Lose every functional word"]],
  ["react-039", 8, "An ex asks for one final night together with no expectations afterward. How do you react?", ["Absolutely not — history already voted", "Tempted, but ask what changed", "Agree only after brutal honesty", "Say yes and accept tomorrow's consequences"]],
  ["react-040", 8, "Your partner admits having a small crush on someone else. What's your first response?", ["Appreciate the honesty", "Ask who and why", "Feel jealous but stay curious", "Question whether it's actually small"]],
  ["react-041", 9, "A trusted partner suggests a roleplay you never imagined them wanting. What do you do?", ["Try it after discussing boundaries", "Ask what part excites them", "Share an equally surprising idea", "Keep it as fantasy until I'm sure"]],
  ["react-042", 9, "Someone gives you an intimate compliment that feels more exposing than being undressed. How do you react?", ["Make a joke to survive it", "Let the moment stay serious", "Ask them to say it again", "Return an even more vulnerable truth"]],
  ["react-043", 9, "Your partner wants to watch you flirt with someone and come home together afterward. What's your response?", ["Intrigued if every boundary is clear", "Hot as fantasy, risky in reality", "Jealous but unexpectedly curious", "Not for me under any rules"]],
  ["react-044", 9, "You receive a very suggestive photo during a serious workday. What do you do?", ["Reply with professional-looking danger", "Save the reaction for later", "Find somewhere private immediately", "Send one sentence that ruins their concentration too"]],
  ["react-045", 9, "A partner asks which fantasy you've been too embarrassed to share. How do you respond?", ["Tell the safest version first", "Ask them to confess simultaneously", "Reveal the real one with clear boundaries", "Need time, but promise an honest answer"]],
  ["react-046", 10, "A close friend admits they once hooked up with your ex and hid it. What do you do first?", ["Ask when it happened", "Focus on the secrecy", "Hear the entire story before reacting", "End one or both relationships immediately"]],
  ["react-047", 10, "Your partner admits they are attracted to your best friend. What's your response?", ["Attraction happens; behavior matters", "Ask whether anything ever happened", "Need distance before discussing it", "Reveal whether I already suspected it"]],
  ["react-048", 10, "Your most private group chat is accidentally projected in front of everyone discussed in it. What's your survival strategy?", ["Apologize with complete honesty", "Stand by the funny parts", "Leave before the scrolling begins", "Ask everyone to reveal their chats too"]],
  ["react-049", 10, "You meet someone with extraordinary chemistry who is clearly unavailable. What do you do?", ["Step away before the story starts", "Keep it friendly with strict distance", "Admit the attraction without acting", "Convince myself one exception is destiny"]],
  ["react-050", 10, "Someone you love asks what part of the relationship you secretly fear losing. How do you answer?", ["The friendship underneath everything", "Feeling completely chosen", "The version of myself I am with them", "The future I already started imagining"]]
], ["reactions", "personal", "relationships"]);

const mostLikelyOptions = ["{{player1}}", "{{player2}}", "Both", "Neither"];

export const mostLikelyToQuestions = buildQuestions([
  ["likely-001", 1, "Who is more likely to turn a quick coffee into a three-hour conversation?", mostLikelyOptions],
  ["likely-002", 1, "Who is more likely to cancel plans and feel immediate peace?", mostLikelyOptions],
  ["likely-003", 1, "Who is more likely to become best friends with a stranger on vacation?", mostLikelyOptions],
  ["likely-004", 1, "Who is more likely to remember one embarrassing moment for ten years?", mostLikelyOptions],
  ["likely-005", 1, "Who is more likely to investigate a new crush like an unpaid detective?", mostLikelyOptions],
  ["likely-006", 3, "Who is more likely to start drama accidentally and then become the mediator?", mostLikelyOptions],
  ["likely-007", 4, "Who is more likely to fall for someone after one perfect playlist?", mostLikelyOptions],
  ["likely-008", 4, "Who is more likely to send a risky message and immediately throw the phone away?", mostLikelyOptions],
  ["likely-009", 5, "Who is more likely to forgive a red flag because the person is hilarious?", mostLikelyOptions],
  ["likely-010", 5, "Who is more likely to secretly enjoy being the subject of gossip?", mostLikelyOptions],
  ["likely-011", 6, "Who is more likely to catch feelings in a supposedly casual situation?", mostLikelyOptions],
  ["likely-012", 6, "Who is more likely to go back to an ex after giving everyone a speech about moving on?", mostLikelyOptions],
  ["likely-013", 7, "Who is more likely to flirt successfully without realizing they're doing it?", mostLikelyOptions],
  ["likely-014", 7, "Who is more likely to keep a friend's scandalous secret forever?", mostLikelyOptions],
  ["likely-015", 8, "Who is more likely to be tempted by someone clearly off-limits?", mostLikelyOptions],
  ["likely-016", 8, "Who is more likely to suggest trying something adventurous first?", mostLikelyOptions],
  ["likely-017", 9, "Who is more likely to enjoy giving up control with someone they completely trust?", mostLikelyOptions],
  ["likely-018", 9, "Who is more likely to consider opening a relationship under the right circumstances?", mostLikelyOptions],
  ["likely-019", 10, "Who is more likely to survive a secret relationship without telling the group chat?", mostLikelyOptions],
  ["likely-020", 10, "Who is more likely to reveal a fantasy that completely changes how everyone sees them?", mostLikelyOptions],
  ["likely-021", 2, "Who is more likely to enter a room and immediately forget why they came?", mostLikelyOptions],
  ["likely-022", 3, "Who is more likely to become emotionally attached to a waiter who remembers their order?", mostLikelyOptions],
  ["likely-023", 4, "Who is more likely to post a subtle thirst trap and swear it wasn't for anyone?", mostLikelyOptions],
  ["likely-024", 4, "Who is more likely to turn a tiny inconvenience into a cinematic monologue?", mostLikelyOptions],
  ["likely-025", 5, "Who is more likely to know a relationship is doomed and stay for one more chapter?", mostLikelyOptions],
  ["likely-026", 5, "Who is more likely to flirt their way out of an awkward situation?", mostLikelyOptions],
  ["likely-027", 5, "Who is more likely to keep screenshots for emotional quality assurance?", mostLikelyOptions],
  ["likely-028", 6, "Who is more likely to become friends with an ex after claiming that never works?", mostLikelyOptions],
  ["likely-029", 6, "Who is more likely to notice tension between two friends before anyone else?", mostLikelyOptions],
  ["likely-030", 6, "Who is more likely to give brilliant dating advice and ignore it personally?", mostLikelyOptions],
  ["likely-031", 7, "Who is more likely to fall for a close friend and hide it badly?", mostLikelyOptions],
  ["likely-032", 7, "Who is more likely to forgive someone after one dangerously good apology?", mostLikelyOptions],
  ["likely-033", 7, "Who is more likely to accidentally expose a secret through facial expressions?", mostLikelyOptions],
  ["likely-034", 7, "Who is more likely to date someone the entire friend group warned them about?", mostLikelyOptions],
  ["likely-035", 7, "Who is more likely to enjoy making a crush slightly jealous?", mostLikelyOptions],
  ["likely-036", 8, "Who is more likely to send the first genuinely suggestive message?", mostLikelyOptions],
  ["likely-037", 8, "Who is more likely to have chemistry with someone at the worst possible time?", mostLikelyOptions],
  ["likely-038", 8, "Who is more likely to kiss a friend and insist it changed nothing?", mostLikelyOptions],
  ["likely-039", 8, "Who is more likely to secretly enjoy being watched while flirting?", mostLikelyOptions],
  ["likely-040", 8, "Who is more likely to break their own dating rule for one specific person?", mostLikelyOptions],
  ["likely-041", 9, "Who is more likely to confess a bold fantasy first?", mostLikelyOptions],
  ["likely-042", 9, "Who is more likely to enjoy being told exactly what to do by someone they trust?", mostLikelyOptions],
  ["likely-043", 9, "Who is more likely to consider inviting a third person under carefully agreed rules?", mostLikelyOptions],
  ["likely-044", 9, "Who is more likely to send a photo that makes the recipient cancel their plans?", mostLikelyOptions],
  ["likely-045", 9, "Who is more likely to be turned on by emotional vulnerability more than appearances?", mostLikelyOptions],
  ["likely-046", 10, "Who is more likely to hide a hookup from the friend group successfully?", mostLikelyOptions],
  ["likely-047", 10, "Who is more likely to be attracted to a best friend's crush and never admit it?", mostLikelyOptions],
  ["likely-048", 10, "Who is more likely to choose intense chemistry over emotional stability?", mostLikelyOptions],
  ["likely-049", 10, "Who is more likely to discover they enjoy a dynamic they once judged?", mostLikelyOptions],
  ["likely-050", 10, "Who is more likely to answer one brutally intimate question with complete honesty?", mostLikelyOptions]
], ["friends", "prediction", "relationships"]);

export const dealbreakerDraftQuestions = buildQuestions([
  ["draft-001", 1, "Draft one travel partner:", ["Perfect planner — takes 200 photos", "Spontaneous adventurer — always late", "Luxury expert — destroys the budget", "Easygoing companion — chooses nothing"]],
  ["draft-002", 1, "Draft one roommate:", ["Cooks every meal — leaves every dish", "Keeps everything spotless — labels your shelves", "Pays early — controls the thermostat", "Never complains — is always home"]],
  ["draft-003", 1, "Draft one best friend:", ["Answers every call — knows no boundaries", "Plans incredible outings — invites extra people", "Keeps every secret — shares none of their own", "Always honest — has no gentle setting"]],
  ["draft-004", 1, "Draft one party personality:", ["Owns the dance floor — vanishes without warning", "Knows everyone — forgets to introduce you", "Brings the fun — creates the cleanup", "Leaves early — takes you with them"]],
  ["draft-005", 1, "Draft one first date:", ["Amazing conversation — terrible restaurant", "Perfect location — awkward silences", "Instant chemistry — two hours late", "Hilarious disaster — no romantic spark"]],
  ["draft-006", 3, "Draft one texting style:", ["Replies instantly — sends twelve messages", "Writes thoughtful essays — replies tomorrow", "Sends elite memes — avoids real questions", "Calls instead — never warns you first"]],
  ["draft-007", 4, "Draft one attractive flaw:", ["Unfairly confident — occasionally arrogant", "Mysterious — impossible to read", "Socially magnetic — flirts with everyone", "Passionate — turns everything into a debate"]],
  ["draft-008", 4, "Draft one relationship perk:", ["Best-friend connection — very little romance", "Constant romance — needs constant reassurance", "Complete independence — rarely checks in", "Total transparency — asks endless questions"]],
  ["draft-009", 5, "Draft one person to bring home:", ["Family adores them — friends are suspicious", "Friends adore them — family starts a committee", "Everyone approves — chemistry is average", "Nobody approves — chemistry is ridiculous"]],
  ["draft-010", 5, "Draft one ex-related complication:", ["Best friends with one ex — tells you everything", "Never mentions exes — still follows all of them", "Hates every ex — claims they were all crazy", "Friendly with all exes — they attend birthdays"]],
  ["draft-011", 6, "Draft one dangerously tempting partner:", ["Emotionally mature — physically predictable", "Incredible chemistry — emotionally inconsistent", "Deeply loyal — intensely jealous", "Completely secure — rarely passionate"]],
  ["draft-012", 6, "Draft one communication package:", ["Radically honest — occasionally brutal", "Always kind — avoids difficult truths", "Excellent listener — shares very little", "Says everything — processes nothing privately"]],
  ["draft-013", 7, "Draft one situationship upgrade:", ["Exclusive — still refuses labels", "Official — keeps the relationship private", "Public and proud — moves far too fast", "Slow and secure — chemistry cools down"]],
  ["draft-014", 7, "Draft one intimacy package:", ["Amazing communication — needs everything scheduled", "Spontaneous chemistry — terrible at feedback", "Very adventurous — easily gets bored", "Deeply affectionate — rarely initiates"]],
  ["draft-015", 8, "Draft one jealousy trade-off:", ["Never jealous — enjoys outside attention", "Protective and passionate — checks in constantly", "Trusts completely — misses obvious flirting", "Admits jealousy — needs lots of reassurance"]],
  ["draft-016", 8, "Draft one fantasy dynamic:", ["They take control — you set every boundary", "You take control — they expect confidence", "You switch roles — neither gets predictable", "You keep it romantic — curiosity remains"]],
  ["draft-017", 9, "Draft one unconventional relationship:", ["Open with strict rules — jealousy is discussed weekly", "Monogamous and intense — privacy is limited", "Independent and flexible — time together is scarce", "Deeply committed — attraction to others is openly discussed"]],
  ["draft-018", 9, "Draft one irresistible complication:", ["Your hottest friend likes them too", "Their ex wants them back", "A coworker openly flirts with them", "Your families already expect marriage"]],
  ["draft-019", 10, "Draft one truth you must accept:", ["They fantasize about someone you know", "They sometimes miss being single", "They once hid feelings for a close friend", "They find stability less exciting than uncertainty"]],
  ["draft-020", 10, "Draft one adventurous agreement:", ["Choose a third person together — no repeats", "Share fantasy lists — nothing is guaranteed", "Attend a private kink event — leave anytime", "Try roleplay as strangers — no real-life questions"]],
  ["draft-021", 2, "Draft one coworker for a difficult project:", ["Brilliant — misses every deadline", "Reliable — schedules endless meetings", "Creative — changes direction daily", "Calm under pressure — contributes only at the end"]],
  ["draft-022", 3, "Draft one group-chat personality:", ["Sends elite memes — ignores serious messages", "Knows every update — creates half the drama", "Always supportive — replies three days later", "Plans every meetup — changes the plan twice"]],
  ["draft-023", 4, "Draft one social-media habit:", ["Posts gorgeous photos — captions are unbearable", "Never posts — watches every story", "Shares everything — hides the relationship", "Has perfect taste — follows every ex"]],
  ["draft-024", 4, "Draft one weekend companion:", ["Always adventurous — never rests", "Perfectly relaxed — refuses decisions", "Finds hidden gems — gets everyone lost", "Plans aesthetic moments — photographs every bite"]],
  ["draft-025", 5, "Draft one crush package:", ["Beautiful voice — terrible texter", "Incredible style — chronically late", "Effortlessly funny — flirts with everyone", "Deeply thoughtful — impossible to read"]],
  ["draft-026", 5, "Draft one dating-app match:", ["Perfect profile — awkward in person", "Terrible profile — electric chemistry", "Replies instantly — interviews you", "Mysterious profile — your friends know them"]],
  ["draft-027", 5, "Draft one apology style:", ["Grand romantic gesture — avoids the actual issue", "Perfect words — repeats the mistake", "Changes behavior — never says sorry", "Completely honest — slightly devastating"]],
  ["draft-028", 6, "Draft one friendship flaw:", ["Fiercely loyal — dislikes everyone you date", "Always available — needs constant access", "Never judges — enables bad decisions", "Pushes you to grow — rarely lets you rest"]],
  ["draft-029", 6, "Draft one attractive personality:", ["Quiet confidence — shares feelings slowly", "Huge personality — needs every room", "Gentle and secure — avoids confrontation", "Ambitious and driven — always working"]],
  ["draft-030", 6, "Draft one conflict style:", ["Talks immediately — says too much", "Takes space — disappears too long", "Stays calm — seems emotionally detached", "Gets emotional — resolves everything honestly"]],
  ["draft-031", 7, "Draft one best-friend complication:", ["They know every secret — remember every mistake", "They defend you publicly — lecture you privately", "They adore your partner — text them independently", "They understand you perfectly — challenge every excuse"]],
  ["draft-032", 7, "Draft one almost-perfect relationship:", ["Peaceful and secure — rarely surprising", "Passionate and exciting — arguments get dramatic", "Independent and trusting — schedules rarely align", "Deeply connected — boundaries need constant work"]],
  ["draft-033", 7, "Draft one person worth risking awkwardness for:", ["Your closest friend — friendship may change", "A coworker — every weekday gets complicated", "A friend's ex — the group will have opinions", "A long-distance crush — chemistry is untested"]],
  ["draft-034", 7, "Draft one romantic gesture:", ["Surprise trip — you hate the destination", "Public declaration — you hate attention", "Handwritten letter — mentions every ex", "Perfect gift — wildly over budget"]],
  ["draft-035", 7, "Draft one secret admirer:", ["Your funniest friend — terrible timing", "A gorgeous stranger — knows too much about you", "Someone unavailable — promises nothing", "Your old crush — returns after your glow-up"]],
  ["draft-036", 8, "Draft one dangerously good flirt:", ["Direct and confident — flirts with everyone", "Quiet and intense — communicates mostly through eye contact", "Playful and teasing — never gets serious", "Sweet and attentive — remembers everything"]],
  ["draft-037", 8, "Draft one chemistry problem:", ["Perfect physical spark — different futures", "Emotional intimacy — attraction grows slowly", "Mutual obsession — terrible timing", "Easy compatibility — one person wants more"]],
  ["draft-038", 8, "Draft one tempting ex:", ["Finally emotionally mature — lives far away", "Still incredible chemistry — same old patterns", "Genuinely apologetic — your friends hate them", "Completely transformed — already dating someone"]],
  ["draft-039", 8, "Draft one flirty friendship:", ["Constant tension — neither admits it", "One past kiss — both call it meaningless", "Everyone assumes you're together — you deny it", "Perfect emotional bond — attraction comes and goes"]],
  ["draft-040", 8, "Draft one trust test:", ["Share locations — preserve phone privacy", "Open phones — never discuss exes", "Tell every fantasy — keep past details private", "Complete independence — disclose every flirtation"]],
  ["draft-041", 9, "Draft one private dynamic:", ["They lead confidently — you define the limits", "You lead completely — they expect creativity", "You switch naturally — control is unpredictable", "Nobody leads — tension builds slowly"]],
  ["draft-042", 9, "Draft one bold invitation:", ["A spontaneous hotel night — phones stay off", "A fantasy-themed date — each brings one surprise", "A private party — leave together anytime", "A no-names roleplay — meet as strangers"]],
  ["draft-043", 9, "Draft one adventurous partner:", ["Open to anything consensual — gets bored easily", "Has specific fantasies — communicates beautifully", "Very experienced — compares without meaning to", "Curious but nervous — trusts you completely"]],
  ["draft-044", 9, "Draft one jealousy arrangement:", ["Flirting is allowed — details are shared", "Fantasy stays private — behavior stays exclusive", "Outside attraction is discussed — nothing is acted on", "One hall pass each — either can cancel the deal"]],
  ["draft-045", 9, "Draft one intimate communication style:", ["Says exactly what they want — expects the same", "Reads every reaction — rarely uses words", "Checks in constantly — interrupts the momentum", "Plans everything together — spontaneity disappears"]],
  ["draft-046", 10, "Draft one friend-group scandal:", ["Secretly dated a friend's ex — years ago", "Had mutual feelings with a best friend — never acted", "Knows about two hidden hookups — protects both", "Once kissed the wrong person — everyone suspects"]],
  ["draft-047", 10, "Draft one difficult truth from a partner:", ["They still think about one ex", "They are attracted to one of your friends", "They sometimes miss being single", "They want more adventure than they admit"]],
  ["draft-048", 10, "Draft one high-risk chemistry:", ["Someone unavailable — feelings are mutual", "Your best friend — timing is terrible", "An ex who changed — trust is damaged", "A stranger who understands you — life goals clash"]],
  ["draft-049", 10, "Draft one fantasy agreement:", ["Invite someone together — friendship circle excluded", "Watch each other flirt — leave together", "Share every fantasy — action is never assumed", "Try one new dynamic — either can stop instantly"]],
  ["draft-050", 10, "Draft one relationship truth serum:", ["Hear their complete fantasy list", "Learn every hidden attraction", "Know what they miss from past relationships", "Discover what they fear telling you"]]
], ["draft", "tradeoffs", "relationships"]);

const redFlagOptions = [
  "Green flag",
  "Needs context",
  "Red flag",
  "Instant exit"
];

export const redFlagRadarQuestions = buildQuestions([
  ["radar-001", 1, "They arrive early for every plan and quietly judge people who are late.", redFlagOptions],
  ["radar-002", 1, "They remember tiny details about you, then use them to prove they know you better than your friends do.", redFlagOptions],
  ["radar-003", 1, "They have a color-coded relationship calendar and want date nights booked two weeks ahead.", redFlagOptions],
  ["radar-004", 1, "They want to spend every weekend together but happily let you choose what you do.", redFlagOptions],
  ["radar-005", 1, "They send good-morning texts every day and notice immediately when your reply feels different.", redFlagOptions],
  ["radar-006", 2, "They say they hate gossip, then somehow know every detail about everyone.", redFlagOptions],
  ["radar-007", 3, "They are extremely close to their family and call them before making any major decision.", redFlagOptions],
  ["radar-008", 3, "They barely text between dates but give you their complete attention whenever you are together.", redFlagOptions],
  ["radar-009", 4, "Their closest friend is an ex, and both insist the breakup was completely mutual.", redFlagOptions],
  ["radar-010", 4, "They never post partners online but document every other part of their life.", redFlagOptions],
  ["radar-011", 4, "They make an effort with your most impressive friends but barely engage with the quieter ones.", redFlagOptions],
  ["radar-012", 4, "They want you to meet their entire friend group after the second date.", redFlagOptions],
  ["radar-013", 5, "They apologize beautifully, but you often have to explain why something hurt first.", redFlagOptions],
  ["radar-014", 5, "They share their location for safety and casually ask why you do not share yours.", redFlagOptions],
  ["radar-015", 5, "Every one of their exes is described as jealous, dramatic, or emotionally unavailable.", redFlagOptions],
  ["radar-016", 5, "They tease you constantly in private but become protective if anyone else does it.", redFlagOptions],
  ["radar-017", 5, "They are still friends with people who have repeatedly cheated on their partners.", redFlagOptions],
  ["radar-018", 6, "They say labels create pressure but expect exclusivity from the beginning.", redFlagOptions],
  ["radar-019", 6, "They ask thoughtful questions about your past but stay vague whenever you ask about theirs.", redFlagOptions],
  ["radar-020", 6, "They need several hours alone after conflict, but always tell you exactly when they will return to the conversation.", redFlagOptions],
  ["radar-021", 6, "They love that you are independent but get disappointed whenever your plans do not include them.", redFlagOptions],
  ["radar-022", 6, "They openly admit they enjoy harmless flirting because it makes them feel attractive.", redFlagOptions],
  ["radar-023", 7, "They say they trust you completely but want to know whenever an ex contacts you.", redFlagOptions],
  ["radar-024", 7, "They compare your relationship to couples online and call it motivation.", redFlagOptions],
  ["radar-025", 7, "They admit they once cheated, explain exactly why, and say they have changed.", redFlagOptions],
  ["radar-026", 7, "They want to move slowly emotionally but act intensely committed whenever the two of you are alone.", redFlagOptions],
  ["radar-027", 7, "They are generous with gifts after arguments but uncomfortable with long emotional conversations.", redFlagOptions],
  ["radar-028", 7, "They tell their best friend almost everything about your relationship, including private arguments.", redFlagOptions],
  ["radar-029", 7, "They say jealousy can be sexy in small doses and occasionally try to provoke yours.", redFlagOptions],
  ["radar-030", 8, "They keep intimate photos from past relationships but insist they never look at them.", redFlagOptions],
  ["radar-031", 8, "They want access to your phone and freely offer access to theirs.", redFlagOptions],
  ["radar-032", 8, "They admit being strongly attracted to one of your friends but promise they would never act on it.", redFlagOptions],
  ["radar-033", 8, "They become much more affectionate in public when someone attractive is paying attention to you.", redFlagOptions],
  ["radar-034", 8, "They say commitment matters more than monogamy and want to discuss what that could mean.", redFlagOptions],
  ["radar-035", 8, "They joke about your private sex life around close friends without checking with you first.", redFlagOptions],
  ["radar-036", 8, "They still occasionally hook up with an ex between relationships and call it convenient.", redFlagOptions],
  ["radar-037", 9, "They want a rule that crushes must be disclosed, even when nobody plans to act on them.", redFlagOptions],
  ["radar-038", 9, "They say fantasy is private and refuse to discuss anything they desire but would not actually do.", redFlagOptions],
  ["radar-039", 9, "They want to explore together but become insecure whenever your curiosity is bolder than theirs.", redFlagOptions],
  ["radar-040", 9, "They suggest watching each other flirt, then admit they already know who they would choose.", redFlagOptions],
  ["radar-041", 9, "They are open about enjoying control in private but expect that dynamic to influence everyday decisions.", redFlagOptions],
  ["radar-042", 9, "They confess a fantasy involving someone you both know and expect credit for being completely honest.", redFlagOptions],
  ["radar-043", 9, "They want complete sexual honesty but prefer not to hear emotional details about your past.", redFlagOptions],
  ["radar-044", 10, "They propose opening the relationship during a period when the two of you already feel disconnected.", redFlagOptions],
  ["radar-045", 10, "They secretly read your messages, confess immediately, and say what they found confirmed their suspicion.", redFlagOptions],
  ["radar-046", 10, "They admit they kissed one of your close friends before you became official and both hid it from you.", redFlagOptions],
  ["radar-047", 10, "They want one consequence-free hall pass but already have a specific person in mind.", redFlagOptions],
  ["radar-048", 10, "They say they love you deeply but are unsure whether lifelong exclusivity fits who they are.", redFlagOptions],
  ["radar-049", 10, "They reveal that your relationship began before they had fully ended their previous one.", redFlagOptions],
  ["radar-050", 10, "They ask you to hide the relationship from their ex because the breakup is still fresh and the ex would be devastated.", redFlagOptions]
], ["dating", "boundaries", "relationships"]);
